function DCM = Decentralize_hy(inppipe, dinp, flag)
%% Initialization 
    Error = 0;
    rootNodes = dlmread('Outlets.txt');
    numofRoots = size(rootNodes,2);
    cutpipe = inppipe(2:numofRoots);  
    parDesign=inppipe(9:size(inppipe,2)); % 这个9其实是8+1. 8是outletIndex的长度. parDesign其实是管道数量65
    INC=dlmread('AhvazINC.txt'); % 这个应该是CANew生成的结果文件 Read the incidence matrix of tree graph generated by loop by loop algorithm 读取由循环逐循环算法生成的树图关联矩阵
    INCorig=INC;%这个不写入
    numofNodes=size(INC,1);
    if numofRoots==1
        INCFinal{1}=INC;
    else
        for i=1:numofRoots
            INCFinal{i}=0;% Final INCs show the final generated layouts saved here. 最终INCs显示保存在这里的最终生成布局。
        end
        INCFinal{1}=INC;

        CutPipeUpDown=zeros(2,numofRoots);% first row the upstrem of cutted pipe second row the downstream
       %% main Body 
        Positions=INC(:,1); % Nodes by positions in matrix
        INC(:,1)=[]; %存储矩阵和向量
        NodeinPart=zeros(numofRoots,numofNodes);%this matrix indicate which nodes contribute in which part of decentralized graph这个矩阵表示哪些节点在去中心化图的哪个部分做出了贡献
        NodeinPart(1,:)=1;%All nodes are in the original graph first 所有节点首先在原始图中
        Rootsp=Num2Pos(rootNodes,numofNodes,Positions);%Position of roots in the INC matrix 在INC矩阵中根的位置
        contribiutingpart = 1;
        Newrootp=Rootsp(1,2);
        oldrootp=Rootsp(1,1);
        if Newrootp==0
            Error=1;
        else
            for z=1:numofRoots-1
                %finding path betwwen two roots and cut a pipe
                Pathp= pathfinder(numofNodes,INC,Newrootp,oldrootp);
                PipesinPath=size(find(Pathp),2) - 3 ; %Number of pipes in paths, candidate for cutting. 为什么减3不是减1
                Cutpipe=round(1+cutpipe(1,z)*(PipesinPath-1));
                Cutpipeupnodep=Pathp(1,Cutpipe+1);
                Cutpipedownnodep=Pathp(1,Cutpipe+2);
                CutPipeUpDown(1,z)=Positions(Cutpipeupnodep);
                CutPipeUpDown(2,z)=Positions(Cutpipedownnodep);
                %Finding nodes in both parts
                NodeinnewPartp = NodeinPartFinder(INC,Cutpipeupnodep,numofNodes);
                NodeinnewPart=Positions(NodeinnewPartp)';
                NodeinPart = NodeinPartupdate(z,NodeinPart,contribiutingpart,NodeinnewPart);
                NodeinoldPart=zeros(1,numofNodes-size(NodeinnewPart,2));
                j=1;
                for i=1:numofNodes
                    if NodeinPart(contribiutingpart,i)==1
                        NodeinoldPart(1,j)=i;
                        j=j+1;
                    end
                end
                %Update INC
                INC(Cutpipeupnodep,Cutpipedownnodep)=0;
                INC(Cutpipedownnodep,Cutpipeupnodep)=0;
                INCFinal{z+1} = divider(NodeinnewPart,INC,Newrootp,Positions);%Update INC
                INCFinal{contribiutingpart} = divider(NodeinoldPart,INC,oldrootp,Positions);%Update INC
                test=INCFinal{1};
                test=test(1,1);
                if test==300000000
                    Error=1;
                    break
                else
                    %Finding new contributing parts
                    if z==numofRoots-1
                        break
                    end
                    Newroot=rootNodes(1,z+2);
                    signal=0;
                    for i=1:numofRoots
                        temp=INCFinal{i};
                        temp=temp(:,1);
                        for j=1:size(temp,1)
                            if temp(j,1)==Newroot
                                signal=1;
                                break
                            end
                        end
                        if signal==1
                            contribiutingpart=i;
                            break
                        end
                    end%find Contributing part
                    %Initialized new part INC Matrix
                    INC=INCFinal{contribiutingpart};    
                    Positions=INC(:,1); % Nodes by positions in matrix
                    INC(:,1)=[];
                    numofNodes = size(INC,1);
                    oldroot = Positions(1,1);
                    oldrootp = 1;
                    Newrootp=Num2Pos(Newroot,numofNodes,Positions);%Position of roots in the INC matrix
                end
            end
        end
     end
    %load('dinp.mat')
    %dinp=dinp(78,:)
    if Error==1
        DCM=300000000;
    else
       objs=Simpleobj(INCFinal);   %%%
       if objs(1,1)>100000 || objs(1,2)>-30 %%%%%%%%%%%%或   ！！！！！！！！！！！！！！！！！
            DCM=objs(1,1)*100000;%成本
%        DCM(1,2)=objs(1,2);%总可持续性
%        DCM(1,3)=objs(1,3);%DC
       else
            save('INCFinal');
            if flag == 1
                DCM = WModoul_hy(parDesign); 
            else
                DCM = LIDModoul_hy(parDesign,dinp);
            end
       end
    end
end


%%
function out = Num2Pos(inp,numofNodes,Positions)%Convert position of nodes to real number of them  将节点的位置转换为它们的实数
    sizeinp=size(inp,2);  
    out=zeros(1,sizeinp);
    for i=1:sizeinp
        for j=1:numofNodes
            if inp(1,i)==Positions(j,1)
                out(1,i)=j;
            end
        end
    end
end

%% path finder algorithm
function out = pathfinder(numofNodes,INC,newrootp,oldrootp)%Convert position of nodes to real number of them
    % PathP=zeros(1,numofNodes);
    Pathp(1,1)=newrootp;
    UpNodep=newrootp;
    k=1;
    % if pathp(1,1)==0
    %     out=0;
    % else
    while UpNodep~=oldrootp
        DownNodeP=UpNodep;
        for i=1:DownNodeP
            if INC(DownNodeP,i)==1
                k=k+1;
                UpNodep=i;
                Pathp(1,k)=UpNodep;
                break
            end
        end
    end
    out=Pathp;
end

%% INC MAKER
function NodeinnewPart = NodeinPartFinder(INC,Cutpipeupnodep,NumofNodes)%Provide NodeinPart function
    savenode=Cutpipeupnodep;    
    NewInc=INC;
    for i=1:NumofNodes%make under main diammeter zero
        for j=1:i
           NewInc(i,j)=0;
        end
    end

    NewNodesPosition=find(NewInc(Cutpipeupnodep,:));
    AddedNodes=NewNodesPosition;

    NumofNew=size(NewNodesPosition,2);
    Sum=NumofNew;
    b=1;
    while b~=0
        num=0;
        for i=1:NumofNew
            Temp=find(NewInc(AddedNodes(1,i),:));
            N=size(Temp,2);
            NewNodesPosition(1,Sum+1:Sum+N)=Temp;
            AddedNodestemp(1,num+1:num+N)=Temp;
            num=num+N;
            Sum=Sum+N;
        end
        AddedNodes=AddedNodestemp;
        AddedNodestemp=0;
        NumofNew=num;
        b=NumofNew;
    end
    a=size(NewNodesPosition,2); 
    b=NewNodesPosition;
    NewNodesPosition(1,1)=savenode;
    NewNodesPosition(2:a+1)=b;
    NodeinnewPart=NewNodesPosition;
end
%%
function out = NodeinPartupdate(Itteration,NodeinPart,contribiutingpart,NodeinnewPart)%update node in part matrix
    for i=1:size(NodeinnewPart,2)
        temp=NodeinnewPart(1,i);
        NodeinPart(contribiutingpart,temp)=0;
        NodeinPart(Itteration+1,temp)=1;
    end
    out =NodeinPart;
end

%% 
function out = divider(NodeinnewPart,INC,Newrootp,Positions)%Update INC
    Erorr=0;
    SizenewInc=size(NodeinnewPart,2);
    NewINC=zeros(SizenewInc,SizenewInc);
    OldINC=INC;
    NewPositions=zeros(SizenewInc,1);
    NewPositions(1,1)=Newrootp;
    newp=find(OldINC(Newrootp,:));
    a=size(newp,2);
    k=1;
    sizetabu=1;
    while k~=SizenewInc
        for i=1:a
            NewPositions(sizetabu+i,1)=newp(1,i);
        end
        q=1;
        for j=1:SizenewInc
            for i=1:a
                if NewPositions(j,1)==newp(1,i)
                    temp(q,1)=j;
                    q=q+1;
                end
            end
        end
        sizetabu=sizetabu+a;
        for i=1:a
            NewINC(k,temp(i,1))=1;
            NewINC(temp(i,1),k)=1;   
        end
        k=k+1;
        Upnodep=NewPositions(k,1);
        if Upnodep==0
           Erorr=1;
           break
        else
            newp=find(OldINC(Upnodep,:));
            t=0;
            for i=1:size(newp,2)
                for j=1:SizenewInc
                    if newp(1,i)==NewPositions(j,1)
                        t=t+1;
                        Tabu(1,t)=i;
                    end
                end
            end
            for i=1:t
                newp(:,Tabu(t))=[];
                Tabu=Tabu-1;
            end
            a=size(newp,2);
        end
        if Erorr==1
            out=zeros(size(NewINC,2),size(NewINC,2)+1);
            out(1,1)=3000000;
        else
            out=zeros(size(NewINC,2),size(NewINC,2)+1);
            % NewPositions可能包含0
            nonZeroIndices = find(NewPositions ~= 0);
            nonZeroPositions = NewPositions(nonZeroIndices);  
            out(nonZeroIndices, 1) = Positions(nonZeroPositions);
            out(:,2:size(NewINC,2)+1)=NewINC; 
        end
    end
end

%%  成本和弹性的简单目标
function cost = Simpleobj(INCFinal)
    %Simple objective for costs and resilience  成本和弹性的简单目标
    %   Calculate area connected to each pipe

    Subcatchout=dlmread('Subcatchout.txt');
    SubcatchmentArea=dlmread('SubcatchmentArea.txt');
    pipes=dlmread('pipes.txt');%%%%%%？
    pipes(:,5)=0;%pipes(:,5) Area directly connected to each upstream pipe  各上游管道直接连接的面积
    for i=1:size(Subcatchout,1)
        for j=1:size(pipes,1)
            if Subcatchout(i,2)==pipes(j,2)
                pipes(j,5)=SubcatchmentArea(i,2);
            end
        end
    end

    itt=size(INCFinal,2);
    % pipes(:,6)=pipes(:,4);
    pipes(:,6)=pipes(:,5);
    for i=1:itt
        numnodes=size(INCFinal{i},1);
        INC=INCFinal{i};
        nodes=INC(:,1);
        INC(:,1)=[];
        for j=numnodes:-1:2
            Currentnode=nodes(j,1);
            conections=find(INC(j,:));
            downnode=nodes(conections(1,1));
            if  size(conections,2)~=1
                conections(1)=[];
                for k=1:size(conections,2)
                    upnodes(1,k)=nodes(conections(1,k),1);
                end
            else
                upnodes=0;
            end

            %Currentpipe
            a=[Currentnode downnode];
            for z=1:size(pipes,1)
                b(1,1)=pipes(z,2);
                b(1,2)=pipes(z,3);
                c(1,1)=pipes(z,3);
                c(1,2)=pipes(z,2);
                if a==b | a==c
                    Currentpipe=z;
                    break
                end
            end
            %UpPipes
            if  upnodes~=0
                Uppipe=zeros(size(upnodes,2),1);
                for y=1:size(upnodes,2)
                    a=[Currentnode upnodes(1,y)];
                    for z=1:size(pipes,1)
                        b(1,1)=pipes(z,2);
                        b(1,2)=pipes(z,3);
                        c(1,1)=pipes(z,3);
                        c(1,2)=pipes(z,2);
                        if a==b | a==c
                            Uppipe(y,1)=z;
                            break
                        end
                     end
                end
            else
                Uppipe=0;
            end
            %QT
            g=1;
            while Uppipe(g,1)~=0 
                pipes(Currentpipe,6)=pipes(Uppipe(g,1),6)+pipes(Currentpipe,6);
                g=g+1;
                 if g>size(Uppipe,1)
                     break
                 end
            end
        end
    end
    %Simple Cost
    c=pipes(:,4).*(pipes(:,6).^0.5);
    cost(1,1)=sum(c);
    pipes(:,7)=2;
    %Area Diammeter 为了减少运算量先算出小管 区分不同的汇水区面积和不透水率
    uselesspipes=zeros(size(pipes,1),1);
    for i=1:size(pipes,1)
        if pipes(i,6)==0
           pipes(i,7)=0.25;
           uselesspipes(i,1)=pipes(i,1);
    %      elseif pipes(i,6)<=1
    %          pipes(i,7)=0.4;
        elseif pipes(i,6)<=1.5
               pipes(i,7)=0.8;
        elseif pipes(i,6)<=5
               pipes(i,7)=1;
        elseif pipes(i,6)<=8
               pipes(i,7)=1.2;
        elseif pipes(i,6)<=13
               pipes(i,7)=1.5;
        else
               pipes(i,7)=2;
        end
     end
    %增加无用管矩阵
    uselesspipes(find(uselesspipes==0))=[];
    dlmwrite('uselesspipes.txt',uselesspipes); 
    dlmwrite('MaxDiametersOptimal.txt',[pipes(:,1) pipes(:,7)]);
    % DC
    %  DC=size(INCFinal,2);
    % if DC>0
    %  cost(1,3)=DC;
    % else
    %     cost(1,3)=100;
    % end

    % % Structure Resilience
    % weights=[1 0.9 0.8 0.7 0.6 0.5 0.4 0.3 0.2 0.1]';
    % Npipes=size(pipes,1);
    % TotalArea=sum(pipes(:,5));
    % categories=zeros(1,10);
    % pipes(:,7)=pipes(:,6)/TotalArea;
    % for j=1:10
    % for i=1:Npipes %#ok<ALIGN>
    %     if pipes(i,7)>((j-1)/10)&&pipes(i,7)<=(j/10)
    %         categories(1,j)=1+categories(1,j);
    %     end
    %     end
    % end
    % cost(1,2)=-100*(categories(1,1)/Npipes)*categories(1,2:10)*weights(2:10,1)/sum(categories(1,2:10));
    % Structure Resilience 2
    Npipes=size(pipes,1);
    TotalArea=sum(pipes(:,5));
    pipes(:,7)=1-(pipes(:,6)/TotalArea);
    NRes90=Npipes;
    summation=0;
    for i=1:Npipes
        if pipes(i,7)<0.9 
            NRes90=NRes90-1;
            summation=summation+pipes(i,7);
        end
    end
    Resilience=-100*(NRes90/Npipes)*(summation/(Npipes-NRes90));
    cost(1,2)=Resilience;
end